package com.abbiya.downloader.greendao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.abbiya.downloader.greendao.Link;

import com.abbiya.downloader.greendao.LinkDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig linkDaoConfig;

    private final LinkDao linkDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        linkDaoConfig = daoConfigMap.get(LinkDao.class).clone();
        linkDaoConfig.initIdentityScope(type);

        linkDao = new LinkDao(linkDaoConfig, this);

        registerDao(Link.class, linkDao);
    }
    
    public void clear() {
        linkDaoConfig.getIdentityScope().clear();
    }

    public LinkDao getLinkDao() {
        return linkDao;
    }

}
